//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.Maintenance_Request = new HashSet<Maintenance_Request>();
        }
    
        public int ApartmentID { get; set; }
        public Nullable<int> VillageID { get; set; }
        public string Apartment_Desc { get; set; }
        public Nullable<int> Build_Num { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Num_Of_Rooms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Request> Maintenance_Request { get; set; }
        public virtual Category Category { get; set; }
        public virtual Village Village { get; set; }
    }
}
