//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Maintenance_Request = new HashSet<Maintenance_Request>();
        }
    
        public int UserID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Access_Code { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<System.DateTime> Employment_Date { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> SalaryID { get; set; }
    
        public virtual Access_Level Access_Level { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Request> Maintenance_Request { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Salary Salary { get; set; }
    }
}
