//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeeID { get; set; }
        public string Fee_Name { get; set; }
        public string Fee_Desc { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
