//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferItem
    {
        public int OrderItemID { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<int> ApartmentID { get; set; }
        public string Accept { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
