//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> RentalID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public byte[] Last_Update { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
